//! ============================================================================
//! [STRAJK FORK] Highlight thread — ephemeral side-discussions about selected text
//! ============================================================================
//!
//! Lets the user select text in a chat message and ask a follow-up question
//! about it without polluting the main session log.
//!
//! Why this lives outside the regular chat pipeline:
//! - The conversation must NOT enter the user's session messages or Claude's
//!   on-disk session store. We use `--no-session-persistence` and write to our
//!   own per-thread NDJSON file under `<app data>/highlight-threads/`.
//! - The Claude process is spawned detached so it keeps running when the user
//!   closes the popover ("revisitable while still working").
//! - Frontend re-attaches to the streaming state via Zustand on popover reopen;
//!   no on-disk thread persistence yet (MVP — easy to revert).
//!
//! This whole module + its 3 Tauri commands + the dispatch arms can be deleted
//! to fully remove the feature.

use std::collections::HashMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::Duration;

use once_cell::sync::Lazy;
use serde::Serialize;
use tauri::AppHandle;

use crate::chat::detached::{is_process_alive, spawn_detached_claude};
use crate::chat::registry;
use crate::chat::tail::{NdjsonTailer, POLL_INTERVAL, POLL_INTERVAL_FAST};
use crate::claude_cli::resolve_cli_binary;
use crate::http_server::EmitExt;

/// Registry key prefix so highlight threads share `PROCESS_REGISTRY` with
/// chat sessions but never collide with a real session id (UUIDs).
fn registry_key(thread_id: &str) -> String {
    format!("highlight-thread:{thread_id}")
}

/// Per-thread NDJSON file under the app data dir.
/// Created lazily on first call.
fn thread_file_path(app: &AppHandle, thread_id: &str) -> Result<PathBuf, String> {
    let data_dir = crate::chat::storage::get_data_dir(app)?;
    let dir = data_dir
        .parent()
        .unwrap_or(&data_dir)
        .join("highlight-threads");
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create highlight-threads dir: {e}"))?;
    // Conservative sanitisation — thread_id is a UUID generated by the frontend
    // but we'd rather not trust it on a filesystem path.
    let safe: String = thread_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect();
    if safe.is_empty() {
        return Err("Invalid thread_id".to_string());
    }
    Ok(dir.join(format!("{safe}.ndjson")))
}

#[derive(Serialize, Clone)]
struct ChunkEvent<'a> {
    thread_id: &'a str,
    content: &'a str,
}

#[derive(Serialize, Clone)]
struct DoneEvent<'a> {
    thread_id: &'a str,
    full_content: &'a str,
}

#[derive(Serialize, Clone)]
struct ErrorEvent<'a> {
    thread_id: &'a str,
    error: &'a str,
}

/// Build the prompt sent to Claude.
///
/// `message_context` is the full text of the source message (post-markdown,
/// passed by the frontend). Including it lets Claude resolve pronouns /
/// references in the highlighted snippet ("this function", "that approach")
/// without needing an extra clarification round-trip. The highlight itself
/// is still the focus — the surrounding message is bracketed as a separate
/// block so the model knows which is which.
fn build_prompt(prompt: &str, quoted_text: &str, message_context: Option<&str>) -> String {
    let context_block = match message_context {
        Some(ctx) if !ctx.trim().is_empty() && ctx.trim() != quoted_text.trim() => {
            format!("<source-message>\n{ctx}\n</source-message>\n\n")
        }
        _ => String::new(),
    };
    format!(
        "The user is asking about a snippet of text they highlighted in a chat conversation. \
         The <highlighted-text> below is the focus of their question; \
         <source-message> (when present) is the surrounding message it was selected from, \
         provided so you can resolve pronouns and references — don't summarise it unless asked. \
         Answer concisely (a few sentences unless more depth is genuinely needed). \
         Do not preface with 'Sure' or 'Great question'.\n\n\
         {context_block}\
         <highlighted-text>\n{quoted_text}\n</highlighted-text>\n\n\
         <user-question>\n{prompt}\n</user-question>"
    )
}

/// Spawn a detached Claude process for an ephemeral highlight thread.
///
/// Returns immediately after spawn. Streaming is delivered via Tauri events
/// `highlight-thread:chunk`, `highlight-thread:done`, `highlight-thread:error`,
/// `highlight-thread:cancelled`, all keyed by `thread_id`.
#[tauri::command]
pub async fn start_highlight_thread(
    app: AppHandle,
    thread_id: String,
    prompt: String,
    quoted_text: String,
    message_context: Option<String>,
    model: Option<String>,
) -> Result<(), String> {
    if thread_id.is_empty() {
        return Err("thread_id is required".to_string());
    }
    if prompt.trim().is_empty() {
        return Err("prompt is required".to_string());
    }

    let cli_path = resolve_cli_binary(&app);
    if !cli_path.exists() {
        return Err("Claude CLI not installed".to_string());
    }

    let output_file = thread_file_path(&app, &thread_id)?;
    // Truncate any pre-existing file from a prior thread with the same id.
    let _ = std::fs::write(&output_file, b"");

    // Stream-json input file: one user message.
    let input_file = output_file.with_extension("in.jsonl");
    {
        let full_prompt = build_prompt(&prompt, &quoted_text, message_context.as_deref());
        let line = serde_json::json!({
            "type": "user",
            "message": { "role": "user", "content": full_prompt },
        });
        let mut f = std::fs::File::create(&input_file)
            .map_err(|e| format!("Failed to create input file: {e}"))?;
        writeln!(f, "{line}").map_err(|e| format!("Failed to write input file: {e}"))?;
    }

    // Working dir doesn't matter much (no tools), but spawn_detached_claude
    // needs an existing path. App data dir always exists.
    let working_dir = output_file
        .parent()
        .ok_or("output_file has no parent")?
        .to_path_buf();

    let model_str = model.as_deref().unwrap_or("claude-sonnet-4-6").to_string();

    let args: Vec<String> = vec![
        "--print".to_string(),
        "--input-format".to_string(),
        "stream-json".to_string(),
        "--output-format".to_string(),
        "stream-json".to_string(),
        "--verbose".to_string(),
        "--model".to_string(),
        model_str,
        "--no-session-persistence".to_string(),
        // No tools: this is a pure Q&A. Prevents Claude from trying to read
        // files or run commands.
        "--allowed-tools".to_string(),
        "".to_string(),
        // Read-only mode as a belt-and-braces guard.
        "--permission-mode".to_string(),
        "plan".to_string(),
        // 2 turns is what one-shot summarization uses; harmless surplus when
        // there are no tools.
        "--max-turns".to_string(),
        "2".to_string(),
    ];

    let pid = spawn_detached_claude(
        &cli_path,
        &args,
        &input_file,
        &output_file,
        &working_dir,
        &[],
    )?;

    let key = registry_key(&thread_id);
    if !registry::register_process(key.clone(), pid) {
        // Cancel was queued before we spawned — the registry already killed PID.
        let _ = app.emit_all(
            "highlight-thread:cancelled",
            &serde_json::json!({ "thread_id": thread_id }),
        );
        return Ok(());
    }

    // Tail in a background thread so this command returns immediately.
    let app_clone = app.clone();
    let output_clone = output_file.clone();
    let thread_id_owned = thread_id.clone();
    std::thread::spawn(move || {
        if let Err(e) = tail_thread(&app_clone, &thread_id_owned, &output_clone, pid) {
            log::error!("[highlight-thread {thread_id_owned}] tail failed: {e}");
            let _ = app_clone.emit_all(
                "highlight-thread:error",
                &ErrorEvent {
                    thread_id: &thread_id_owned,
                    error: &e,
                },
            );
        }
        registry::unregister_process(&registry_key(&thread_id_owned));
    });

    Ok(())
}

/// Cancel a running highlight thread (SIGKILL the detached Claude process).
///
/// We bypass `registry::cancel_process` because it's session-id-aware and
/// emits `chat:cancelled` events / writes to run-log manifests that don't
/// apply here. The tail thread will notice the dead process within ~2s and
/// emit `highlight-thread:error` on its own (and clean up the global
/// PROCESS_REGISTRY entry); we just need to kill the PID ourselves.
#[tauri::command]
pub async fn cancel_highlight_thread(thread_id: String) -> Result<(), String> {
    use crate::platform::{kill_process, kill_process_tree};

    if let Some(pid) = HIGHLIGHT_PIDS
        .lock()
        .ok()
        .and_then(|mut m| m.remove(&registry_key(&thread_id)))
    {
        let _ = kill_process_tree(pid);
        let _ = kill_process(pid);
    }
    Ok(())
}

/// Local PID registry. Duplicates the entry that lives in the global
/// PROCESS_REGISTRY so `cancel_highlight_thread` can kill the PID without
/// needing an `AppHandle` or adding accessors on the shared registry.
static HIGHLIGHT_PIDS: Lazy<Mutex<HashMap<String, u32>>> = Lazy::new(|| Mutex::new(HashMap::new()));

fn remember_pid(key: &str, pid: u32) {
    if let Ok(mut m) = HIGHLIGHT_PIDS.lock() {
        m.insert(key.to_string(), pid);
    }
}

fn forget_pid(key: &str) {
    if let Ok(mut m) = HIGHLIGHT_PIDS.lock() {
        m.remove(key);
    }
}

/// Tail the per-thread NDJSON file and emit chunk/done events.
/// Mirrors the simpler half of `tail_claude_output`, stripped of session
/// management, tool calls, and Monitor handling (none apply here).
fn tail_thread(
    app: &AppHandle,
    thread_id: &str,
    output_file: &Path,
    pid: u32,
) -> Result<(), String> {
    remember_pid(&registry_key(thread_id), pid);

    // Output file is created by the shell redirect. Wait briefly for it to
    // exist (rare race in tests / very fast spawns).
    let mut waited = 0u32;
    while !output_file.exists() && waited < 200 {
        std::thread::sleep(Duration::from_millis(10));
        waited += 10;
    }
    let mut tailer = NdjsonTailer::new_from_start(output_file)?;
    let mut full_content = String::new();
    let mut last_emitted_len = 0usize;
    let mut completed = false;
    let mut last_data_at = std::time::Instant::now();

    loop {
        let lines = tailer.poll()?;
        let had_data = !lines.is_empty();
        if had_data {
            last_data_at = std::time::Instant::now();
        }

        for line in lines {
            let parsed: serde_json::Value = match serde_json::from_str(&line) {
                Ok(v) => v,
                Err(_) => continue,
            };
            let msg_type = parsed.get("type").and_then(|t| t.as_str());

            // Stream text from assistant messages. Each "assistant" line in
            // Claude's stream-json output carries the cumulative content so
            // far for that turn — we diff against what we've emitted to send
            // only the new tail as a chunk.
            if msg_type == Some("assistant") {
                if let Some(content) = parsed
                    .get("message")
                    .and_then(|m| m.get("content"))
                    .and_then(|c| c.as_array())
                {
                    let mut turn_text = String::new();
                    for block in content {
                        if block.get("type").and_then(|t| t.as_str()) == Some("text") {
                            if let Some(text) = block.get("text").and_then(|t| t.as_str()) {
                                turn_text.push_str(text);
                            }
                        }
                    }
                    // Build the new running content (prior turns + this turn).
                    // For our single-turn use case there's typically only one
                    // assistant message, so `full_content` ends up == turn_text.
                    let new_total_len = full_content.len() + turn_text.len();
                    if new_total_len > last_emitted_len {
                        // Emit only the delta beyond what we've already sent.
                        let delta_start = last_emitted_len.saturating_sub(full_content.len());
                        let delta: &str = if delta_start < turn_text.len() {
                            &turn_text[delta_start..]
                        } else {
                            ""
                        };
                        if !delta.is_empty() {
                            let _ = app.emit_all(
                                "highlight-thread:chunk",
                                &ChunkEvent {
                                    thread_id,
                                    content: delta,
                                },
                            );
                            last_emitted_len += delta.len();
                        }
                    }
                }
            }

            if msg_type == Some("result") {
                // Final turn — capture full text and break.
                if let Some(result_str) = parsed.get("result").and_then(|r| r.as_str()) {
                    if full_content.is_empty() {
                        full_content = result_str.to_string();
                        // If we never emitted from assistant blocks (some
                        // configurations skip them), emit the result as one
                        // chunk so the UI gets text.
                        if last_emitted_len == 0 && !full_content.is_empty() {
                            let _ = app.emit_all(
                                "highlight-thread:chunk",
                                &ChunkEvent {
                                    thread_id,
                                    content: &full_content,
                                },
                            );
                            last_emitted_len = full_content.len();
                        }
                    }
                }
                completed = true;
                break;
            }
        }

        if completed {
            break;
        }

        // Liveness check: process gone AND no data for >2s → assume crashed.
        if !is_process_alive(pid) && last_data_at.elapsed() > Duration::from_secs(2) {
            log::warn!("[highlight-thread {thread_id}] process {pid} gone, ending tail");
            break;
        }

        std::thread::sleep(if had_data {
            POLL_INTERVAL_FAST
        } else {
            POLL_INTERVAL
        });
    }

    forget_pid(&registry_key(thread_id));

    if completed {
        let _ = app.emit_all(
            "highlight-thread:done",
            &DoneEvent {
                thread_id,
                full_content: &full_content,
            },
        );
    } else {
        // Process exited without a result line — emit error so the UI can show
        // "Interrupted". Don't surface raw stdout (could be huge).
        let _ = app.emit_all(
            "highlight-thread:error",
            &ErrorEvent {
                thread_id,
                error: "Claude exited without producing a result",
            },
        );
    }

    // Best-effort cleanup of temp files. Keeping the output around could be
    // useful for debugging but for an MVP we want zero footprint.
    let _ = std::fs::remove_file(output_file);
    let _ = std::fs::remove_file(output_file.with_extension("in.jsonl"));

    Ok(())
}
